[package]
name = "yewcounter"
version = "0.1.0"
authors = ["Sage Mitchell <dev@mx00s.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4.20"
wasm-bindgen = "0.2.67"
yew = "0.17.4"
